### ISSUE TITLE
.html.erb files not recognized

### ISSUE THREAD

**Issue by dogweather** [AtomLinter/linter-erb#11] opened 2015-11-12 00:32 UTC
The linter is great, but only seems to be triggered on .erb files. And it seems that by default, an HTML linter is working on .html.erb files. 

Anyone know where the fix for this would lie?

**Comment by Arcanemagus** [comment] 2015-11-12 01:23
Can you run `Log Cursor Scope` in the file? Both in a "regular" HTML part, and part of the templated Ruby part? I'm guessing at least one of those sections has the wrong scope being applied.

**Comment by dogweather** [comment] 2015-11-12 07:51
Interesting. When in an HTML part, it's:

<img width="462" alt="screen shot 2015-11-11 at 11 49 37 pm" src="https://cloud.githubusercontent.com/assets/150670/11113125/ee4937d4-88ce-11e5-878c-a09c227ffc79.png">

And in an erb tag:

<img width="468" alt="screen shot 2015-11-11 at 11 50 55 pm" src="https://cloud.githubusercontent.com/assets/150670/11113139/15d3e7a4-88cf-11e5-8191-dddf294c6965.png">

Here's the full screen:

![screen shot 2015-11-11 at 11 48 41 pm](https://cloud.githubusercontent.com/assets/150670/11113142/26b9f202-88cf-11e5-821f-e536310c2920.png)

**Comment by dogweather** [comment] 2015-11-12 07:55
Here are another couple, logged when the cursor is in the 'error' region:

<img width="913" alt="screen shot 2015-11-11 at 11 53 08 pm" src="https://cloud.githubusercontent.com/assets/150670/11113170/7001c9c6-88cf-11e5-9582-aa1f97c9b36a.png">

<img width="910" alt="screen shot 2015-11-11 at 11 54 03 pm" src="https://cloud.githubusercontent.com/assets/150670/11113187/869fa91e-88cf-11e5-9cab-631d4a1eb61e.png">

<img width="910" alt="screen shot 2015-11-11 at 11 55 19 pm" src="https://cloud.githubusercontent.com/assets/150670/11113205/b213d3f4-88cf-11e5-9ee3-c2430cc6f136.png">

Thank you!

**Comment by Arcanemagus** [comment] 2015-11-12 08:13
So it looks like this linter would trigger in all of those situations as it identifies itself as being able to handle anything under the `text.html.erb` or `text.html.ruby` scopes... the issue is that this has never been updates to the current Linter API and as such will _never_ run, any messages you are seeing come from a different `linter-*` provider.

Would you be interested in updating this linter so it can be used again? Or are you still interested in maintaining this @eXprojects?

**Comment by dogweather** [comment] 2015-11-12 08:48
So you mean that actually, `linter-erb` isn't even running — these messages are coming from another linter? So would that mean that there are two issues, 1) update `linter-erb` to the new api, and 2) update the other linter not to run on `.erb` files?

**Comment by rcsole** [comment] 2015-12-28 18:12
Since it seems like nobody has given this a short I'm happy to work a pure JS version of this.

**Comment by Arcanemagus** [comment] 2015-12-28 18:17
@rcsole great! We look forward to your PR!

**Comment by Arcanemagus** [comment] 2015-12-28 18:21
@rcsole [linter-eslint](https://github.com/AtomLinter/linter-eslint) is another good example of a pure JS one.

**Comment by Arcanemagus** [comment] 2016-01-05 23:22
@ricardograca or @rcsole are either of you planning on re-implementing this linter? If not I'll give it a shot sometime soon.

**Comment by Arcanemagus** [comment] 2016-01-05 23:22
Marking this particular issue as a duplicate of #9.

**Closed by Arcanemagus** 2016-01-05 23:22 UTC

**Comment by ricardograca** [comment] 2016-01-06 11:23
@Arcanemagus Sorry for the lack of activity, but I haven't used the ERB linter for a while so I currently have no plans for working on this. I'll keep an eye open for this though.
