### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by akissa** [AtomLinter/linter-erb#10] opened 2015-07-10 15:01 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (/Users/andrew/.atom/packages/linter/lib/main.coffee:57:8)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
```

**Comment by jmangt** [comment] 2015-07-11 19:28
:+1:

**Comment by jakeprime** [comment] 2015-07-17 09:34
+1

**Comment by j-p-r** [comment] 2015-07-18 09:37
same here

**Comment by ApfelUser** [comment] 2015-07-21 15:54
:+1: same here

**Comment by mnort9** [comment] 2015-07-24 21:45
+1

**Comment by HeartBreakOne** [comment] 2015-07-27 23:07
+1

**Comment by h-michael** [comment] 2015-08-19 08:13
:+1

**Comment by iashanmugavel** [comment] 2015-09-14 08:46
+1

**Comment by Arcanemagus** [comment] 2015-11-12 08:15
Duplicate of #9, marking as closed. If anyone in this thread is interested in still using this linter a PR updating it to the new API would be welcome!

**Closed by Arcanemagus** 2015-11-12 08:15 UTC
